default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  reconnect: false

development:
  <<: *default
  database: rails-3-2-test01-development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: rails-3-2-test01-test
  username: root
  password:
  socket: /tmp/mysql.sock
