source 'https://rubygems.org'
gem 'rails', '3.2.16'
gem 'mysql2'

# group :assets do
#   gem 'sass-rails',   '~> 3.2.3'
#   gem 'coffee-rails', '~> 3.2.1'
#   gem 'uglifier', '>= 1.0.3'
# end

group :development do
  gem 'pry-rails'
  # gem 'better_errors'
  # gem 'binding_of_caller'
end

group :development, :test do
  gem 'rspec-rails'
  gem "factory_girl_rails"
  gem 'pry-byebug'
end
